// Current executable guidance; dated audits and decision records retain historical commands.
export const COMMAND_DOCUMENTS = Object.freeze([
  'README.md',
  'AGENTS.md',
  'docs/README.md',
  'docs/usage/userscript.md',
  'docs/usage/settings.md',
  'docs/usage/troubleshooting.md',
  'docs/browser-extension.md',
  'docs/model-cache-strategy.md',
  'docs/model-worker-ops.md',
  'docs/onnx-runtime.md',
  'docs/architecture/overview.md',
  'docs/architecture/browser-runtime.md',
  'docs/architecture/extension-runtime.md',
  'docs/architecture/model-service.md',
  'docs/development/commands.md',
  'docs/development/verification.md',
  'docs/development/releases.md',
  'docs/development/contributing.md',
  'docs/development/directory-layout.md',
  'docs/development/documentation.md',
  'docs/reference/model-worker-http.md',
])
