name = "hv-pony-models"
main = "src/index.ts"
compatibility_date = "2026-05-18"

routes = [
  { pattern = "models.ngnl.host", custom_domain = true }
]

[vars]
PUBLIC_MODEL_PATH = "/yolo26n-640.onnx"
REAL_MODEL_OBJECT_KEY = "real/yolo26n-640.onnx"
DECOY_MODEL_OBJECT_KEY = "decoy/yolo26n-640.onnx"
PUBLIC_ORT_MODEL_PATH = "/yolo26n-640.ort"
REAL_ORT_MODEL_OBJECT_KEY = "yolo26n-640.ort"
PUBLIC_RUNTIME_WASM_PATH = "/runtime/ort-wasm-simd-25d707460dd5286203299356b17f4262ace93b712e4708b893d4cfd902da2aaa.wasm"
RUNTIME_WASM_OBJECT_KEY = "runtime/ort-wasm-simd-25d707460dd5286203299356b17f4262ace93b712e4708b893d4cfd902da2aaa.wasm"
INVALID_KEY_MODE = "${INVALID_KEY_MODE}"

[[kv_namespaces]]
binding = "MODEL_KEYS"
id = "${MODEL_KEYS_KV_NAMESPACE_ID}"

[[r2_buckets]]
binding = "MODEL_BUCKET"
bucket_name = "${MODEL_BUCKET_NAME}"
